#!/usr/bin/php
<?php

use Knp\Provider\ConsoleServiceProvider;

include __DIR__ . '/../config/app.php';
$app = include __DIR__ . '/bootstrap.php';

$app->register(new ConsoleServiceProvider(), array(
    'console.name'              => 'URL Shortener Command Line Interface',
    'console.version'           => '1.0.0-alpha',
    'console.project_directory' => __DIR__ . '/..',
));

$console = $app['console'];
$console->add(new Chocopoche\Silex\Console\DBCreateDatabase);
$console->add(new Chocopoche\Silex\Console\DBImportSchema);
$console->add(new Chocopoche\Silex\Console\ShortenLast);
$console->add(new Chocopoche\Silex\Console\ShortenAdd);
$console->add(new Chocopoche\Silex\Console\ShortenResolve);

$console->run();
